# -*- coding: utf-8 -*-
"""kütüphaneyönetimsistemi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r05Dx94PTwTOq7GlgpJIy49N9XAENwbH
"""

class Library:
    def __init__(self):
        self.file = "books.txt"
        self.file_handler = open(self.file, "a+")

    def __del__(self):
        self.file_handler.close()


    def kitap_listele(self):
        self.file_handler.seek(0)
        kitaplar = self.file_handler.readlines()
        for kitap in kitaplar:
            kitap_bilgi = kitap.strip().split(',')
            print(f"Kitap: {kitap_bilgi[0]}, Yazar: {kitap_bilgi[1]}")

    def kitap_ekle(self):
        kitap_ad= input("Kitap adını girin: ")
        kitap_yazar = input("Yazar adını girin: ")
        yayin_yil = input("Yayın yılını girin: ")
        sayfa_sayi = input("Sayfa sayısını girin: ")
        kitap_bilgi = f"{kitap_ad},{ kitap_yazar},{yayin_yil},{sayfa_sayi}\n"
        self.file_handler.write(kitap_bilgi)
        print("Kitap başarıyla eklendi!")

    def kitap_sil(self):
        kitap_ad = input("Kaldırmak istediğiniz kitabın adını girin: ")
        x = False
        self.file_handler.close()
        with open(self.file, "r") as f:
            kitaplar = f.readlines()
        with open(self.file, "w") as f:
            for kitap in kitaplar:
                if kitap_ad != kitap.strip().split(',')[0]:
                    f.write(kitap)
                else:
                    x = True
        if x:
            print("Kitap kaldırıldı.")
        else:
            print("Listede kitap bulunamadı.")
        self.file_handler = open(self.file, "a+")


lib = Library()

while True:
    print("\n*** MENÜ ***")
    print("1) Kitapları Listele")
    print("2) Kitap Ekle")
    print("3) Kitap Kaldır")
    print("q) Çıkış")

    secim = input("Seçiminizi yapın: ")

    if secim == '1':
        lib.kitap_listele()
    elif secim == '2':
        lib.kitap_ekle()
    elif secim == '3':
        lib.kitap_sil()
    elif secim == "q":
        print("Programdan çıkılıyor...")
        break
    else:
        print("Geçersiz seçim. Lütfen 1 ile 3 arasında bir sayı girin.")